FROM node:18-alpine AS builder

WORKDIR /app

COPY cmd/web/package.json cmd/web/yarn.lock ./

RUN yarn install --frozen-lockfile

COPY cmd/web/ .

ARG VITE_API_BASE_URL

ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}

RUN yarn build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

COPY cmd/web/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]