DROP TRIGGER IF EXISTS update_relationships_updated_at ON relationships;
DROP TRIGGER IF EXISTS update_users_updated_at ON users;
DROP FUNCTION IF EXISTS update_updated_at_column();
DROP INDEX IF EXISTS idx_relationships_requester_addressee;
DROP INDEX IF EXISTS idx_relationships_actioned_at;
DROP INDEX IF EXISTS idx_relationships_addressee_status;
DROP INDEX IF EXISTS idx_relationships_requester_status;
DROP INDEX IF EXISTS idx_relationships_deleted_at;
DROP TABLE IF EXISTS relationships;
DROP INDEX IF EXISTS idx_users_username;
DROP INDEX IF EXISTS idx_users_email;
DROP INDEX IF EXISTS idx_users_deleted_at;
DROP TABLE IF EXISTS users;
DROP EXTENSION IF EXISTS "pgcrypto";
DROP EXTENSION IF EXISTS "uuid-ossp";
